sudo : required
language: generic
services:
  - docker

before_install:
  - docker build  -t onurcaydere/docker -f Dockerfile.dev .
script:
  - docker run -e CI=true onurcaydere/docker npm run test

#buraya kadar olan travisden build kontrolünü sağlıyor.

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app : "docker1"
  env: "Docker1-env"
  bucket_name: "elasticbeanstalk-us-east-2-860003904213"
  bucket_path: "docker1"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
